# deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-k8s-app
  labels:
    app: python-k8s-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: python-k8s-app
  template:
    metadata:
      labels:
        app: python-k8s-app
    spec:
      containers:
      - name: python-k8s-app
        image: REPLACE_IMAGE_HERE
        imagePullPolicy: Always
        ports:
        - containerPort: 5000
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
