# deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-k8s-app
  labels:
    app: python-k8s-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: python-k8s-app
  template:
    metadata:
      labels:
        app: python-k8s-app
    spec:
      containers:
      - name: python-k8s-app
        image: surendranaidu/python-k8s-app:latest
        ports:
        - containerPort: 5000

