apiVersion: v1
kind: ConfigMap
metadata:
  name: python-flask-config
data:
  app.py: |
    from flask import Flask
    app = Flask(__name__)

    @app.route('/')
    def hello_world():
        return "Hello, World! Surendra"

    if __name__ == "__main__":
        app.run(host='0.0.0.0', port=5000)
