# service.yaml
apiVersion: v1
kind: Service
metadata:
  name: python-k8s-app-service
spec:
  selector:
    app: python-k8s-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
  type: LoadBalancer

