---

### **2. `manifests/`**

#### **`prometheus-slo-config.yaml`**
```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: slo-config
  namespace: monitoring
data:
  slo.yaml: |
    objectives:
      - name: "http_request_availability"
        target: 99.9
        success:
          query: sum(rate(http_requests_total{status=~"2.."}[1m]))
        total:
          query: sum(rate(http_requests_total[1m]))
