apiVersion: apps/v1
kind: Deployment
metadata:
  name: slo-exporter
  namespace: monitoring
spec:
  replicas: 1
  selector:
    matchLabels:
      app: slo-exporter
  template:
    metadata:
      labels:
        app: slo-exporter
    spec:
      containers:
        - name: slo-exporter
          image: ghcr.io/castai/prometheus-slo-exporter:latest
          ports:
            - containerPort: 8080
          volumeMounts:
            - mountPath: /config
              name: slo-config
      volumes:
        - name: slo-config
          configMap:
            name: slo-config
