apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: prometheus
  namespace: default
rules:
- apiGroups: [""]
  resources: ["pods", "services", "nodes", "endpoints"]
  verbs: ["get", "list", "watch"]

