apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus
  namespace: monitoring
spec:
  project: default
  source:
    repoURL: https://github.com/surendranaidu/k8_minikube_automation
    targetRevision: main
    path: argocd-deploy/prometheus
    helm:
      valueFiles:
        - values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
