name: CI Pipeline for Flask App

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    # Checkout the code
    - name: Checkout repository
      uses: actions/checkout@v3

    # Set up Docker
    - name: Set up Docker
      uses: docker/setup-buildx-action@v2

    # Log in to Docker Hub
    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    # Build and push Docker image with version tag
    - name: Build and push Docker image
      run: |
        VERSION=$(date +%Y%m%d%H%M%S)  # Create a version based on the current timestamp
        docker build -t ${{ secrets.DOCKER_USERNAME }}/python-k8s-app:$VERSION -f application/Dockerfile application/
        docker push ${{ secrets.DOCKER_USERNAME }}/python-k8s-app:$VERSION

    # Commit and push version change to Git
    - name: Commit and push version change to Git
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        git add .
        git commit -m "Update version to $VERSION"
        git tag $VERSION  # Tag the commit with the version
        git push origin main
        git push origin $VERSION  # Push the tag to the repository

    # Set up kubectl to interact with Kubernetes
    - name: Set up kubectl
      uses: azure/setup-kubectl@v3
      with:
        version: 'latest'

    # Configure kubectl using the stored kubeconfig secret
    - name: Configure kubectl
      run: |
        echo "${{ secrets.KUBECONFIG }}" > $HOME/.kube/config

    # Update deployment.yaml with the new version tag
    - name: Update deployment.yaml with version
      run: |
        sed -i 's|image: ${{ secrets.DOCKER_USERNAME }}/python-k8s-app:.*|image: ${{ secrets.DOCKER_USERNAME }}/python-k8s-app:$VERSION|' application/deployment.yaml

    # Deploy the application to Kubernetes
    - name: Deploy to Kubernetes
      run: |
        kubectl apply -f application/deployment.yaml
        kubectl apply -f application/service.yaml
