name: CI Pipeline for Flask App

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    # Checkout the code
    - name: Checkout repository
      uses: actions/checkout@v3

    # Set up Docker
    - name: Set up Docker
      uses: docker/setup-buildx-action@v2

    # Log in to Docker Hub
    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    # Build and push Docker image with version tag
    - name: Build and push Docker image
      id: build-and-push
      run: |
        VERSION=$(date +%Y%m%d%H%M%S)  # Create a version based on current time
        DOCKER_USERNAME=${{ secrets.DOCKER_USERNAME }}
        IMAGE=$DOCKER_USERNAME/python-k8s-app:$VERSION
        docker build -t $IMAGE -f application/Dockerfile application/
        docker push $IMAGE
        echo "VERSION=$VERSION" >> $GITHUB_ENV
        echo "IMAGE=$IMAGE" >> $GITHUB_ENV

    # Replace image placeholder in deployment.yaml
    - name: Update deployment.yaml with version
      run: |
        IMAGE=${{ env.IMAGE }}
        sed -i "s|image: .*|image: $IMAGE|" application/deployment.yaml
        echo "Updated deployment.yaml with image: $IMAGE"

    # Debug deployment.yaml
    - name: Print deployment.yaml
      run: cat application/deployment.yaml

    # Commit and push updated deployment.yaml
    - name: Commit and push version change to Git
      run: |
        git config --global user.name "surendranaidu"
        git add application/deployment.yaml
        if ! git diff --cached --quiet; then
          git commit -m "Update deployment.yaml with image version ${{ env.VERSION }}"
          git push origin main
        else
          echo "No changes to commit"
        fi
