name: CI Pipeline for Flask App

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    # Checkout the code
    - name: Checkout repository
      uses: actions/checkout@v3

    # Check Git version
    - name: Check Git version
      run: git --version

    # Set up Docker
    - name: Set up Docker
      uses: docker/setup-buildx-action@v2

    # Log in to Docker Hub
    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    # Build and push Docker image with version tag
    - name: Build and push Docker image
      id: build-and-push  # Add an ID to reference the output later
      run: |
        VERSION=$(date +%Y%m%d%H%M%S)  # Create a version based on current time
        DOCKER_USERNAME=${{ secrets.DOCKER_USERNAME }}
        IMAGE=$DOCKER_USERNAME/python-k8s-app:$VERSION
        docker build -t $IMAGE -f application/Dockerfile application/
        docker push $IMAGE
        echo "VERSION=$VERSION" >> $GITHUB_ENV  # Save VERSION for reuse

    # Replace image placeholder in deployment.yaml
    - name: Update deployment.yaml with version
      run: |
        DOCKER_USERNAME=${{ secrets.DOCKER_USERNAME }}
        sed -i "s|REPLACE_IMAGE_HERE|$DOCKER_USERNAME/python-k8s-app:${{ env.VERSION }}|" application/deployment.yaml

    # Commit and push updated deployment.yaml
    - name: Commit and push version change to Git
      run: |
        git config --global user.name "surendranaidu"
        git config --global user.email "pattipatisurendra@gmail.com"
        
        git add application/deployment.yaml
        if ! git diff --cached --quiet; then
          git commit -m "Update deployment.yaml with image version ${{ env.VERSION }}"
          git push origin main
        else
          echo "No changes to commit"
        fi
